export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  CAPITAL: '/capital',
  INSTRUMENTS: '/instruments',
  TRADE_JOURNAL: '/trade-journal',
  ANALYTICS: '/analytics',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  SETTINGS_INSTRUMENTS: '/settings/instruments',
  SETTINGS_ENTRY_REASONS: '/settings/entry-reasons',
  SETTINGS_EXIT_REASONS: '/settings/exit-reasons',
  SETTINGS_TIMEFRAMES: '/settings/timeframes',
  SETTINGS_EMOTIONS: '/settings/emotions',
  SETTINGS_MISTAKES: '/settings/mistakes',
}
